# Generated by Django 2.2.4 on 2021-02-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_login', '0002_users_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthdate',
            field=models.DateTimeField(),
        ),
    ]
